- name: Install and Configure PostgreSQL
  hosts: instances
  user: ubuntu
  become: true

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:

    - name: Install PostgreSQL
      apt:
        name: postgresql